// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class TetherStoreError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "TetherStoreError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? TetherStoreError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum TetherStoreApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class TetherStoreApiPigeonCodecReader: FlutterStandardReader {
}

private class TetherStoreApiPigeonCodecWriter: FlutterStandardWriter {
}

private class TetherStoreApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TetherStoreApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TetherStoreApiPigeonCodecWriter(data: data)
  }
}

class TetherStoreApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = TetherStoreApiPigeonCodec(readerWriter: TetherStoreApiPigeonCodecReaderWriter())
}

/// Durable key/value storage for the shell, owned by the platform.
///
/// Synchronous on purpose. Both implementations are a `UserDefaults` or a
/// `SharedPreferences` read, which are memory lookups after the first touch,
/// and making them `@async` would buy nothing but a suspend function on each
/// side. Dart still sees futures — every Pigeon host call is asynchronous from
/// Dart regardless — so the restore-before-first-frame path is unaffected.
///
/// There is no `isSupported()` here, unlike `UnplugHostApi`. A store either
/// answers or it does not, and the Dart side treats a throwing channel as
/// "no platform" — see `lib/tether/state/session_store.dart`. Adding a probe
/// method would mean two ways for the same absence to be reported.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TetherStoreApi {
  /// The value written under [key], or null when nothing is stored there.
  ///
  /// Null is the answer for "never written" as well as for "removed". The
  /// shell has no use for the difference: a missing snapshot and a deleted one
  /// both mean the session starts empty.
  func read(key: String) throws -> String?
  func write(key: String, value: String) throws
  func remove(key: String) throws
  /// Wipes every key this store owns.
  ///
  /// Exists for the `export_and_delete` safeguard, which asks that deletion be
  /// "completed rather than hidden". [remove] would be enough for today's one
  /// key; [clear] is what stays correct when a second key is added and someone
  /// forgets to extend the delete path.
  func clear() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TetherStoreApiSetup {
  static var codec: FlutterStandardMessageCodec { TetherStoreApiPigeonCodec.shared }
  /// Sets up an instance of `TetherStoreApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TetherStoreApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// The value written under [key], or null when nothing is stored there.
    ///
    /// Null is the answer for "never written" as well as for "removed". The
    /// shell has no use for the difference: a missing snapshot and a deleted one
    /// both mean the session starts empty.
    let readChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tether_health.TetherStoreApi.read\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          let result = try api.read(key: keyArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      readChannel.setMessageHandler(nil)
    }
    let writeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tether_health.TetherStoreApi.write\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! String
        do {
          try api.write(key: keyArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      writeChannel.setMessageHandler(nil)
    }
    let removeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tether_health.TetherStoreApi.remove\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        do {
          try api.remove(key: keyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeChannel.setMessageHandler(nil)
    }
    /// Wipes every key this store owns.
    ///
    /// Exists for the `export_and_delete` safeguard, which asks that deletion be
    /// "completed rather than hidden". [remove] would be enough for today's one
    /// key; [clear] is what stays correct when a second key is added and someone
    /// forgets to extend the delete path.
    let clearChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tether_health.TetherStoreApi.clear\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearChannel.setMessageHandler { _, reply in
        do {
          try api.clear()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearChannel.setMessageHandler(nil)
    }
  }
}
