// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.TetherHealthLLC.tetherhealth.store

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object TetherStoreApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class TetherStoreApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

/**
 * Durable key/value storage for the shell, owned by the platform.
 *
 * Synchronous on purpose. Both implementations are a `UserDefaults` or a
 * `SharedPreferences` read, which are memory lookups after the first touch,
 * and making them `@async` would buy nothing but a suspend function on each
 * side. Dart still sees futures — every Pigeon host call is asynchronous from
 * Dart regardless — so the restore-before-first-frame path is unaffected.
 *
 * There is no `isSupported()` here, unlike `UnplugHostApi`. A store either
 * answers or it does not, and the Dart side treats a throwing channel as
 * "no platform" — see `lib/tether/state/session_store.dart`. Adding a probe
 * method would mean two ways for the same absence to be reported.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface TetherStoreApi {
  /**
   * The value written under [key], or null when nothing is stored there.
   *
   * Null is the answer for "never written" as well as for "removed". The
   * shell has no use for the difference: a missing snapshot and a deleted one
   * both mean the session starts empty.
   */
  fun read(key: String): String?
  fun write(key: String, value: String)
  fun remove(key: String)
  /**
   * Wipes every key this store owns.
   *
   * Exists for the `export_and_delete` safeguard, which asks that deletion be
   * "completed rather than hidden". [remove] would be enough for today's one
   * key; [clear] is what stays correct when a second key is added and someone
   * forgets to extend the delete path.
   */
  fun clear()

  companion object {
    /** The codec used by TetherStoreApi. */
    val codec: MessageCodec<Any?> by lazy {
      TetherStoreApiPigeonCodec()
    }
    /** Sets up an instance of `TetherStoreApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TetherStoreApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.TetherStoreApi.read$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.read(keyArg))
            } catch (exception: Throwable) {
              TetherStoreApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.TetherStoreApi.write$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.write(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              TetherStoreApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.TetherStoreApi.remove$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.remove(keyArg)
              listOf(null)
            } catch (exception: Throwable) {
              TetherStoreApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.TetherStoreApi.clear$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clear()
              listOf(null)
            } catch (exception: Throwable) {
              TetherStoreApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
