#!/usr/bin/env python3
"""Regenerates design/copy-review.md from the two sources of unreviewed copy.

Run after editing assets/design/supplement.content.lookup.en.json or any
TODO(copy) marker in lib/tether/screens/shell/.

    python3 tool/extract_copy_review.py

The point of the file it writes is that the review burden is legible. "82
TODOs" is not something anybody can act on; a list of every sentence, split by
which kind of reviewer it needs, is.
"""
import re
import json
import pathlib
import collections

ROOT = pathlib.Path(__file__).resolve().parent.parent

shell = collections.OrderedDict()
for path in sorted((ROOT / 'lib/tether/screens/shell').glob('*.dart')):
    lines = path.read_text().splitlines()
    hits = []
    for i, line in enumerate(lines):
        if 'TODO(copy)' not in line:
            continue
        note = line.split('TODO(copy):')[-1].strip()
        window = '\n'.join(lines[i:i + 8])
        strings = re.findall(r"'((?:[^'\\]|\\.){3,})'", window)
        strings = [s for s in strings
                   if not s.startswith(('/', 'package:')) and ' ' in s]
        hits.append((i + 1, note, strings[:3]))
    if hits:
        shell[path.name] = hits

supplement = json.loads(
    (ROOT / 'assets/design/supplement.content.lookup.en.json').read_text()
)


def screen_strings(s):
    out = []
    for key in ('title', 'headline', 'sub', 'footer'):
        if s.get(key):
            out.append((key, s[key]))
    for n, b in enumerate(s.get('blocks', [])):
        for key in ('eyebrow', 'title', 'body', 'pill', 'label', 'quote',
                    'value', 'mid', 'left', 'right', 'foot'):
            if b.get(key):
                out.append((f'block{n}.{key}', str(b[key])))
        for c in (b.get('chips') or b.get('items') or []):
            if isinstance(c, str):
                out.append((f'block{n}.chip', c))
            elif isinstance(c, dict):
                for k in ('title', 'body'):
                    if c.get(k):
                        out.append((f'block{n}.option.{k}', c[k]))
            elif isinstance(c, list) and len(c) == 2:
                out.append((f'block{n}.row', f'{c[0]} — {c[1]}'))
    for a in s.get('actions', []):
        out.append(('action', a.get('label', '')))
    return out


total_sup = sum(len(screen_strings(v)) for v in supplement['screens'].values())
total_shell = sum(len(h) for h in shell.values())

lines = []
w = lines.append
w('# Copy review pack')
w('')
w('Every patient-facing string in this app that **nobody has reviewed**.')
w('')
w('Two sources, and they need different reviewers:')
w('')
w(f'- **Programme copy** — {total_sup} strings across the '
  f'{len(supplement["screens"])} LookUp screens written in this')
w('  repository (`assets/design/supplement.content.lookup.en.json`). These are '
  'read')
w('  by a person in a health programme, several of them at their worst moment.')
w('  They need clinical review. Each renders behind a "NOT CLINICALLY REVIEWED"')
w('  notice until that happens.')
w(f'- **Shell chrome** — {total_shell} marked sites across the six host '
  'screens. These are')
w('  navigation and control labels, not programme content, so most need an '
  'editor')
w('  rather than a clinician. The exceptions are called out below.')
w('')
w('Generated by `tool/extract_copy_review.py`. Regenerate after changing '
  'either source.')
w('')
w('## 1 · Programme copy — needs clinical review')
w('')
for sid in ['S02', 'S04', 'S06', 'S10', 'S15',
            'S16', 'S24', 'S25', 'S26', 'S28']:
    s = supplement['screens'].get(sid)
    if not s:
        continue
    w(f'### {sid} — {s.get("title", "(no title)")}')
    w('')
    for where, text in screen_strings(s):
        w(f'- `{where}` — {text}')
    w('')
w('## 2 · Shell chrome — needs an editor, not a clinician')
w('')
w('Exceptions that DO need clinical sign-off, because they describe what '
  'happens')
w("to a person's data or route them to help:")
w('')
w('- `crisis_route_screen.dart` — every string on the crisis route. It is the '
  'one')
w('  screen `shell.json` says is identical everywhere and never reordered.')
w('- `record_screen.dart` — the delete-confirmation body. It states exactly '
  'what is')
w('  and is not destroyed, and it must stay true of the build it ships in.')
w('- `program_join_screen.dart` — the measure-flag wording and the')
w('  "this area can tell you to call someone" card, which describe clinical')
w('  thresholds.')
w('')
for name, hits in shell.items():
    w(f'### {name}')
    w('')
    for ln, note, strings in hits:
        w(f'- **L{ln}** — {note}')
        for s in strings:
            w(f'  - `{s}`')
    w('')

(ROOT / 'design/copy-review.md').write_text('\n'.join(lines) + '\n')
print(f'wrote design/copy-review.md: {total_sup} programme strings, '
      f'{total_shell} shell sites')
