// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.TetherHealthLLC.tetherhealth.unplug

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object UnplugApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Which authorization iOS is being asked for.
 *
 * `child` is the one that needs an iCloud Family and the guardian's Screen
 * Time passcode (§3.1). Android ignores the distinction.
 */
enum class PlatformAuthorizationMode(val raw: Int) {
  INDIVIDUAL(0),
  CHILD(1);

  companion object {
    fun ofRaw(raw: Int): PlatformAuthorizationMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The outcome of asking for authorization. */
enum class PlatformAuthorizationStatus(val raw: Int) {
  NOT_REQUESTED(0),
  APPROVED(1),
  DENIED(2),
  /**
   * iOS only: the device is not in an iCloud Family, so a child device cannot
   * be shielded at all. No amount of retrying changes this.
   */
  BLOCKED_NO_FAMILY_SHARING(3),
  /** The platform has no screen-time API this build can use. */
  UNAVAILABLE(4);

  companion object {
    fun ofRaw(raw: Int): PlatformAuthorizationStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** What a session or shield applies to. */
enum class PlatformShieldScope(val raw: Int) {
  SELECTED_APPS(0),
  EVERYTHING_EXCEPT_ALLOWLIST(1);

  companion object {
    fun ofRaw(raw: Int): PlatformShieldScope? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Which gate the intercept offers, when the tier calls for one. */
enum class PlatformEffortGate(val raw: Int) {
  NONE(0),
  BREATH(1),
  COMMITMENT(2),
  PUZZLE(3);

  companion object {
    fun ofRaw(raw: Int): PlatformEffortGate? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * The live configuration the intercept reads.
 *
 * This is what lands in the App Group container on iOS, where the extensions
 * pick it up; on Android it is held by the foreground service.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformModuleConfig (
  val tier: Long,
  val overrideAllowance: Long,
  val overridesUsed: Long,
  val gate: PlatformEffortGate,
  val strict: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformModuleConfig {
      val tier = pigeonVar_list[0] as Long
      val overrideAllowance = pigeonVar_list[1] as Long
      val overridesUsed = pigeonVar_list[2] as Long
      val gate = pigeonVar_list[3] as PlatformEffortGate
      val strict = pigeonVar_list[4] as Boolean
      return PlatformModuleConfig(tier, overrideAllowance, overridesUsed, gate, strict)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      tier,
      overrideAllowance,
      overridesUsed,
      gate,
      strict,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformModuleConfig
    return UnplugApiPigeonUtils.deepEquals(this.tier, other.tier) && UnplugApiPigeonUtils.deepEquals(this.overrideAllowance, other.overrideAllowance) && UnplugApiPigeonUtils.deepEquals(this.overridesUsed, other.overridesUsed) && UnplugApiPigeonUtils.deepEquals(this.gate, other.gate) && UnplugApiPigeonUtils.deepEquals(this.strict, other.strict)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.tier)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.overrideAllowance)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.overridesUsed)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.gate)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.strict)
    return result
  }
  override fun toString(): String {
    return "PlatformModuleConfig(tier=$tier, overrideAllowance=$overrideAllowance, overridesUsed=$overridesUsed, gate=$gate, strict=$strict)"
  }
}

/**
 * The apps the person chose, as the module is allowed to describe them.
 *
 * There are no app identifiers here on purpose. iOS cannot give them, and
 * carrying them on Android only would make the two platforms tell a care team
 * different stories (§1). The native side holds the real selection privately.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformAppSelection (
  val groupLabels: List<String>,
  val groupAppCounts: List<Long>,
  val totalApps: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformAppSelection {
      val groupLabels = pigeonVar_list[0] as List<String>
      val groupAppCounts = pigeonVar_list[1] as List<Long>
      val totalApps = pigeonVar_list[2] as Long
      return PlatformAppSelection(groupLabels, groupAppCounts, totalApps)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      groupLabels,
      groupAppCounts,
      totalApps,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformAppSelection
    return UnplugApiPigeonUtils.deepEquals(this.groupLabels, other.groupLabels) && UnplugApiPigeonUtils.deepEquals(this.groupAppCounts, other.groupAppCounts) && UnplugApiPigeonUtils.deepEquals(this.totalApps, other.totalApps)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.groupLabels)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.groupAppCounts)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.totalApps)
    return result
  }
  override fun toString(): String {
    return "PlatformAppSelection(groupLabels=$groupLabels, groupAppCounts=$groupAppCounts, totalApps=$totalApps)"
  }
}

/**
 * The budgets that fire a threshold callback.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformThresholds (
  val minutes: List<Long>,
  val opens: List<Long>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformThresholds {
      val minutes = pigeonVar_list[0] as List<Long>
      val opens = pigeonVar_list[1] as List<Long>
      return PlatformThresholds(minutes, opens)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      minutes,
      opens,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformThresholds
    return UnplugApiPigeonUtils.deepEquals(this.minutes, other.minutes) && UnplugApiPigeonUtils.deepEquals(this.opens, other.opens)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.minutes)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.opens)
    return result
  }
  override fun toString(): String {
    return "PlatformThresholds(minutes=$minutes, opens=$opens)"
  }
}

/**
 * One named app with a real duration. Android only — see [PlatformUsage].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformAppUsage (
  val label: String,
  val minutes: Long,
  val opens: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformAppUsage {
      val label = pigeonVar_list[0] as String
      val minutes = pigeonVar_list[1] as Long
      val opens = pigeonVar_list[2] as Long
      return PlatformAppUsage(label, minutes, opens)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      label,
      minutes,
      opens,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformAppUsage
    return UnplugApiPigeonUtils.deepEquals(this.label, other.label) && UnplugApiPigeonUtils.deepEquals(this.minutes, other.minutes) && UnplugApiPigeonUtils.deepEquals(this.opens, other.opens)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.label)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.minutes)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.opens)
    return result
  }
  override fun toString(): String {
    return "PlatformAppUsage(label=$label, minutes=$minutes, opens=$opens)"
  }
}

/**
 * What the platform will actually report for a window of days.
 *
 * [perApp] is empty on iOS and populated on Android. [opensAreApproximate] is
 * true on iOS, where the count is derived from shield events rather than real
 * launches, and every surface that shows it must say so.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformUsage (
  val dailyMinutes: List<Long>,
  val daypartMinutes: List<Long>,
  val opens: Long,
  val opensAreApproximate: Boolean,
  val perApp: List<PlatformAppUsage>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformUsage {
      val dailyMinutes = pigeonVar_list[0] as List<Long>
      val daypartMinutes = pigeonVar_list[1] as List<Long>
      val opens = pigeonVar_list[2] as Long
      val opensAreApproximate = pigeonVar_list[3] as Boolean
      val perApp = pigeonVar_list[4] as List<PlatformAppUsage>
      return PlatformUsage(dailyMinutes, daypartMinutes, opens, opensAreApproximate, perApp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      dailyMinutes,
      daypartMinutes,
      opens,
      opensAreApproximate,
      perApp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformUsage
    return UnplugApiPigeonUtils.deepEquals(this.dailyMinutes, other.dailyMinutes) && UnplugApiPigeonUtils.deepEquals(this.daypartMinutes, other.daypartMinutes) && UnplugApiPigeonUtils.deepEquals(this.opens, other.opens) && UnplugApiPigeonUtils.deepEquals(this.opensAreApproximate, other.opensAreApproximate) && UnplugApiPigeonUtils.deepEquals(this.perApp, other.perApp)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.dailyMinutes)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.daypartMinutes)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.opens)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.opensAreApproximate)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.perApp)
    return result
  }
  override fun toString(): String {
    return "PlatformUsage(dailyMinutes=$dailyMinutes, daypartMinutes=$daypartMinutes, opens=$opens, opensAreApproximate=$opensAreApproximate, perApp=$perApp)"
  }
}

/**
 * One item of the tracking health check (§2.2).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformTrackingCheck (
  val name: String,
  val healthy: Boolean,
  val detail: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformTrackingCheck {
      val name = pigeonVar_list[0] as String
      val healthy = pigeonVar_list[1] as Boolean
      val detail = pigeonVar_list[2] as String
      return PlatformTrackingCheck(name, healthy, detail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      healthy,
      detail,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformTrackingCheck
    return UnplugApiPigeonUtils.deepEquals(this.name, other.name) && UnplugApiPigeonUtils.deepEquals(this.healthy, other.healthy) && UnplugApiPigeonUtils.deepEquals(this.detail, other.detail)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.name)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.healthy)
    result = 31 * result + UnplugApiPigeonUtils.deepHash(this.detail)
    return result
  }
  override fun toString(): String {
    return "PlatformTrackingCheck(name=$name, healthy=$healthy, detail=$detail)"
  }
}
private open class UnplugApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformAuthorizationMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformAuthorizationStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformShieldScope.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PlatformEffortGate.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformModuleConfig.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformAppSelection.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformThresholds.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformAppUsage.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformUsage.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformTrackingCheck.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PlatformAuthorizationMode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformAuthorizationStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformShieldScope -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformEffortGate -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is PlatformModuleConfig -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PlatformAppSelection -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PlatformThresholds -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PlatformAppUsage -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is PlatformUsage -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is PlatformTrackingCheck -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Calls Dart makes into the platform.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface UnplugHostApi {
  /**
   * False on web, desktop, and any build without the screen-time layer. Dart
   * falls back to its own simulation when this is false.
   */
  fun isSupported(): Boolean
  suspend fun requestAuthorization(mode: PlatformAuthorizationMode): PlatformAuthorizationStatus
  fun authorizationStatus(): PlatformAuthorizationStatus
  /**
   * Presents the system app picker. Returns the number of apps chosen.
   *
   * The picker is a system component on both platforms and cannot be drawn by
   * Flutter, which is why this returns a count and not a list.
   */
  suspend fun presentAppPicker(): Long
  fun applyShield(config: PlatformModuleConfig, selection: PlatformAppSelection)
  fun liftShield(reason: String)
  fun startSession(durationSeconds: Long, scope: PlatformShieldScope, strict: Boolean)
  fun endSession(overrideReason: String?)
  fun setThresholds(thresholds: PlatformThresholds)
  /** Reads the last [days] days. Shaped to the iOS floor on both platforms. */
  suspend fun readUsage(days: Long): PlatformUsage
  fun trackingHealth(): List<PlatformTrackingCheck>
  /**
   * Deletes everything the module holds on this device.
   *
   * Called by the retention sweep (§3.2) and by account deletion.
   */
  fun purgeLocalData(olderThanDays: Long)

  companion object {
    /** The codec used by UnplugHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      UnplugApiPigeonCodec()
    }
    /** Sets up an instance of `UnplugHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UnplugHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.UnplugHostApi.isSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isSupported())
            } catch (exception: Throwable) {
              UnplugApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.UnplugHostApi.requestAuthorization$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as PlatformAuthorizationMode
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestAuthorization(modeArg))
              } catch (exception: Throwable) {
                UnplugApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.UnplugHostApi.authorizationStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.authorizationStatus())
            } catch (exception: Throwable) {
              UnplugApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.UnplugHostApi.presentAppPicker$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.presentAppPicker())
              } catch (exception: Throwable) {
                UnplugApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.UnplugHostApi.applyShield$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as PlatformModuleConfig
            val selectionArg = args[1] as PlatformAppSelection
            val wrapped: List<Any?> = try {
              api.applyShield(configArg, selectionArg)
              listOf(null)
            } catch (exception: Throwable) {
              UnplugApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.UnplugHostApi.liftShield$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reasonArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.liftShield(reasonArg)
              listOf(null)
            } catch (exception: Throwable) {
              UnplugApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.UnplugHostApi.startSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val durationSecondsArg = args[0] as Long
            val scopeArg = args[1] as PlatformShieldScope
            val strictArg = args[2] as Boolean
            val wrapped: List<Any?> = try {
              api.startSession(durationSecondsArg, scopeArg, strictArg)
              listOf(null)
            } catch (exception: Throwable) {
              UnplugApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.UnplugHostApi.endSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val overrideReasonArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.endSession(overrideReasonArg)
              listOf(null)
            } catch (exception: Throwable) {
              UnplugApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.UnplugHostApi.setThresholds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val thresholdsArg = args[0] as PlatformThresholds
            val wrapped: List<Any?> = try {
              api.setThresholds(thresholdsArg)
              listOf(null)
            } catch (exception: Throwable) {
              UnplugApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.UnplugHostApi.readUsage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val daysArg = args[0] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.readUsage(daysArg))
              } catch (exception: Throwable) {
                UnplugApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.UnplugHostApi.trackingHealth$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.trackingHealth())
            } catch (exception: Throwable) {
              UnplugApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.tether_health.UnplugHostApi.purgeLocalData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val olderThanDaysArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.purgeLocalData(olderThanDaysArg)
              listOf(null)
            } catch (exception: Throwable) {
              UnplugApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Callbacks the platform makes into Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class UnplugFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by UnplugFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      UnplugApiPigeonCodec()
    }
  }
  suspend fun onThresholdCrossed(minutesUsedArg: Long, opensArg: Long)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.tether_health.UnplugFlutterApi.onThresholdCrossed$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(minutesUsedArg, opensArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(UnplugApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onShieldShown(groupLabelArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.tether_health.UnplugFlutterApi.onShieldShown$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(groupLabelArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(UnplugApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onShieldDismissed(groupLabelArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.tether_health.UnplugFlutterApi.onShieldDismissed$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(groupLabelArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(UnplugApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onOverrideUsed(groupLabelArg: String, overridesRemainingArg: Long)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.tether_health.UnplugFlutterApi.onOverrideUsed$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(groupLabelArg, overridesRemainingArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(UnplugApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  /**
   * Fired when a health check starts failing, so the person is told rather
   * than left believing the module is still running (§2.2).
   */
  suspend fun onTrackingStopped(checkNameArg: String, detailArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.tether_health.UnplugFlutterApi.onTrackingStopped$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(checkNameArg, detailArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(UnplugApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
