// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum UnplugApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Which authorization iOS is being asked for.
///
/// `child` is the one that needs an iCloud Family and the guardian's Screen
/// Time passcode (§3.1). Android ignores the distinction.
enum PlatformAuthorizationMode: Int, CaseIterable {
  case individual = 0
  case child = 1
}

/// The outcome of asking for authorization.
enum PlatformAuthorizationStatus: Int, CaseIterable {
  case notRequested = 0
  case approved = 1
  case denied = 2
  /// iOS only: the device is not in an iCloud Family, so a child device cannot
  /// be shielded at all. No amount of retrying changes this.
  case blockedNoFamilySharing = 3
  /// The platform has no screen-time API this build can use.
  case unavailable = 4
}

/// What a session or shield applies to.
enum PlatformShieldScope: Int, CaseIterable {
  case selectedApps = 0
  case everythingExceptAllowlist = 1
}

/// Which gate the intercept offers, when the tier calls for one.
enum PlatformEffortGate: Int, CaseIterable {
  case none = 0
  case breath = 1
  case commitment = 2
  case puzzle = 3
}

/// The live configuration the intercept reads.
///
/// This is what lands in the App Group container on iOS, where the extensions
/// pick it up; on Android it is held by the foreground service.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformModuleConfig: Hashable, CustomStringConvertible {
  var tier: Int64
  var overrideAllowance: Int64
  var overridesUsed: Int64
  var gate: PlatformEffortGate
  var strict: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformModuleConfig? {
    let tier = pigeonVar_list[0] as! Int64
    let overrideAllowance = pigeonVar_list[1] as! Int64
    let overridesUsed = pigeonVar_list[2] as! Int64
    let gate = pigeonVar_list[3] as! PlatformEffortGate
    let strict = pigeonVar_list[4] as! Bool

    return PlatformModuleConfig(
      tier: tier,
      overrideAllowance: overrideAllowance,
      overridesUsed: overridesUsed,
      gate: gate,
      strict: strict
    )
  }
  func toList() -> [Any?] {
    return [
      tier,
      overrideAllowance,
      overridesUsed,
      gate,
      strict,
    ]
  }
  static func == (lhs: PlatformModuleConfig, rhs: PlatformModuleConfig) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return UnplugApiPigeonInternal.deepEquals(lhs.tier, rhs.tier) && UnplugApiPigeonInternal.deepEquals(lhs.overrideAllowance, rhs.overrideAllowance) && UnplugApiPigeonInternal.deepEquals(lhs.overridesUsed, rhs.overridesUsed) && UnplugApiPigeonInternal.deepEquals(lhs.gate, rhs.gate) && UnplugApiPigeonInternal.deepEquals(lhs.strict, rhs.strict)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformModuleConfig")
    UnplugApiPigeonInternal.deepHash(value: tier, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: overrideAllowance, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: overridesUsed, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: gate, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: strict, hasher: &hasher)
  }

  public var description: String {
    return "PlatformModuleConfig(tier: \(String(describing: tier)), overrideAllowance: \(String(describing: overrideAllowance)), overridesUsed: \(String(describing: overridesUsed)), gate: \(String(describing: gate)), strict: \(String(describing: strict)))"
  }
}

/// The apps the person chose, as the module is allowed to describe them.
///
/// There are no app identifiers here on purpose. iOS cannot give them, and
/// carrying them on Android only would make the two platforms tell a care team
/// different stories (§1). The native side holds the real selection privately.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformAppSelection: Hashable, CustomStringConvertible {
  var groupLabels: [String]
  var groupAppCounts: [Int64]
  var totalApps: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformAppSelection? {
    let groupLabels = pigeonVar_list[0] as! [String]
    let groupAppCounts = pigeonVar_list[1] as! [Int64]
    let totalApps = pigeonVar_list[2] as! Int64

    return PlatformAppSelection(
      groupLabels: groupLabels,
      groupAppCounts: groupAppCounts,
      totalApps: totalApps
    )
  }
  func toList() -> [Any?] {
    return [
      groupLabels,
      groupAppCounts,
      totalApps,
    ]
  }
  static func == (lhs: PlatformAppSelection, rhs: PlatformAppSelection) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return UnplugApiPigeonInternal.deepEquals(lhs.groupLabels, rhs.groupLabels) && UnplugApiPigeonInternal.deepEquals(lhs.groupAppCounts, rhs.groupAppCounts) && UnplugApiPigeonInternal.deepEquals(lhs.totalApps, rhs.totalApps)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformAppSelection")
    UnplugApiPigeonInternal.deepHash(value: groupLabels, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: groupAppCounts, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: totalApps, hasher: &hasher)
  }

  public var description: String {
    return "PlatformAppSelection(groupLabels: \(String(describing: groupLabels)), groupAppCounts: \(String(describing: groupAppCounts)), totalApps: \(String(describing: totalApps)))"
  }
}

/// The budgets that fire a threshold callback.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformThresholds: Hashable, CustomStringConvertible {
  var minutes: [Int64]
  var opens: [Int64]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformThresholds? {
    let minutes = pigeonVar_list[0] as! [Int64]
    let opens = pigeonVar_list[1] as! [Int64]

    return PlatformThresholds(
      minutes: minutes,
      opens: opens
    )
  }
  func toList() -> [Any?] {
    return [
      minutes,
      opens,
    ]
  }
  static func == (lhs: PlatformThresholds, rhs: PlatformThresholds) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return UnplugApiPigeonInternal.deepEquals(lhs.minutes, rhs.minutes) && UnplugApiPigeonInternal.deepEquals(lhs.opens, rhs.opens)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformThresholds")
    UnplugApiPigeonInternal.deepHash(value: minutes, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: opens, hasher: &hasher)
  }

  public var description: String {
    return "PlatformThresholds(minutes: \(String(describing: minutes)), opens: \(String(describing: opens)))"
  }
}

/// One named app with a real duration. Android only — see [PlatformUsage].
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformAppUsage: Hashable, CustomStringConvertible {
  var label: String
  var minutes: Int64
  var opens: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformAppUsage? {
    let label = pigeonVar_list[0] as! String
    let minutes = pigeonVar_list[1] as! Int64
    let opens = pigeonVar_list[2] as! Int64

    return PlatformAppUsage(
      label: label,
      minutes: minutes,
      opens: opens
    )
  }
  func toList() -> [Any?] {
    return [
      label,
      minutes,
      opens,
    ]
  }
  static func == (lhs: PlatformAppUsage, rhs: PlatformAppUsage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return UnplugApiPigeonInternal.deepEquals(lhs.label, rhs.label) && UnplugApiPigeonInternal.deepEquals(lhs.minutes, rhs.minutes) && UnplugApiPigeonInternal.deepEquals(lhs.opens, rhs.opens)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformAppUsage")
    UnplugApiPigeonInternal.deepHash(value: label, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: minutes, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: opens, hasher: &hasher)
  }

  public var description: String {
    return "PlatformAppUsage(label: \(String(describing: label)), minutes: \(String(describing: minutes)), opens: \(String(describing: opens)))"
  }
}

/// What the platform will actually report for a window of days.
///
/// [perApp] is empty on iOS and populated on Android. [opensAreApproximate] is
/// true on iOS, where the count is derived from shield events rather than real
/// launches, and every surface that shows it must say so.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformUsage: Hashable, CustomStringConvertible {
  var dailyMinutes: [Int64]
  var daypartMinutes: [Int64]
  var opens: Int64
  var opensAreApproximate: Bool
  var perApp: [PlatformAppUsage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformUsage? {
    let dailyMinutes = pigeonVar_list[0] as! [Int64]
    let daypartMinutes = pigeonVar_list[1] as! [Int64]
    let opens = pigeonVar_list[2] as! Int64
    let opensAreApproximate = pigeonVar_list[3] as! Bool
    let perApp = pigeonVar_list[4] as! [PlatformAppUsage]

    return PlatformUsage(
      dailyMinutes: dailyMinutes,
      daypartMinutes: daypartMinutes,
      opens: opens,
      opensAreApproximate: opensAreApproximate,
      perApp: perApp
    )
  }
  func toList() -> [Any?] {
    return [
      dailyMinutes,
      daypartMinutes,
      opens,
      opensAreApproximate,
      perApp,
    ]
  }
  static func == (lhs: PlatformUsage, rhs: PlatformUsage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return UnplugApiPigeonInternal.deepEquals(lhs.dailyMinutes, rhs.dailyMinutes) && UnplugApiPigeonInternal.deepEquals(lhs.daypartMinutes, rhs.daypartMinutes) && UnplugApiPigeonInternal.deepEquals(lhs.opens, rhs.opens) && UnplugApiPigeonInternal.deepEquals(lhs.opensAreApproximate, rhs.opensAreApproximate) && UnplugApiPigeonInternal.deepEquals(lhs.perApp, rhs.perApp)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformUsage")
    UnplugApiPigeonInternal.deepHash(value: dailyMinutes, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: daypartMinutes, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: opens, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: opensAreApproximate, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: perApp, hasher: &hasher)
  }

  public var description: String {
    return "PlatformUsage(dailyMinutes: \(String(describing: dailyMinutes)), daypartMinutes: \(String(describing: daypartMinutes)), opens: \(String(describing: opens)), opensAreApproximate: \(String(describing: opensAreApproximate)), perApp: \(String(describing: perApp)))"
  }
}

/// One item of the tracking health check (§2.2).
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformTrackingCheck: Hashable, CustomStringConvertible {
  var name: String
  var healthy: Bool
  var detail: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformTrackingCheck? {
    let name = pigeonVar_list[0] as! String
    let healthy = pigeonVar_list[1] as! Bool
    let detail = pigeonVar_list[2] as! String

    return PlatformTrackingCheck(
      name: name,
      healthy: healthy,
      detail: detail
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      healthy,
      detail,
    ]
  }
  static func == (lhs: PlatformTrackingCheck, rhs: PlatformTrackingCheck) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return UnplugApiPigeonInternal.deepEquals(lhs.name, rhs.name) && UnplugApiPigeonInternal.deepEquals(lhs.healthy, rhs.healthy) && UnplugApiPigeonInternal.deepEquals(lhs.detail, rhs.detail)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformTrackingCheck")
    UnplugApiPigeonInternal.deepHash(value: name, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: healthy, hasher: &hasher)
    UnplugApiPigeonInternal.deepHash(value: detail, hasher: &hasher)
  }

  public var description: String {
    return "PlatformTrackingCheck(name: \(String(describing: name)), healthy: \(String(describing: healthy)), detail: \(String(describing: detail)))"
  }
}

private class UnplugApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformAuthorizationMode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformAuthorizationStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformShieldScope(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformEffortGate(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return PlatformModuleConfig.fromList(self.readValue() as! [Any?])
    case 134:
      return PlatformAppSelection.fromList(self.readValue() as! [Any?])
    case 135:
      return PlatformThresholds.fromList(self.readValue() as! [Any?])
    case 136:
      return PlatformAppUsage.fromList(self.readValue() as! [Any?])
    case 137:
      return PlatformUsage.fromList(self.readValue() as! [Any?])
    case 138:
      return PlatformTrackingCheck.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class UnplugApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PlatformAuthorizationMode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformAuthorizationStatus {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformShieldScope {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformEffortGate {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformModuleConfig {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformAppSelection {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformThresholds {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformAppUsage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformUsage {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformTrackingCheck {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class UnplugApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return UnplugApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return UnplugApiPigeonCodecWriter(data: data)
  }
}

class UnplugApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = UnplugApiPigeonCodec(readerWriter: UnplugApiPigeonCodecReaderWriter())
}


/// Calls Dart makes into the platform.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol UnplugHostApi {
  /// False on web, desktop, and any build without the screen-time layer. Dart
  /// falls back to its own simulation when this is false.
  func isSupported() throws -> Bool
  func requestAuthorization(mode: PlatformAuthorizationMode) async throws -> PlatformAuthorizationStatus
  func authorizationStatus() throws -> PlatformAuthorizationStatus
  /// Presents the system app picker. Returns the number of apps chosen.
  ///
  /// The picker is a system component on both platforms and cannot be drawn by
  /// Flutter, which is why this returns a count and not a list.
  func presentAppPicker() async throws -> Int64
  func applyShield(config: PlatformModuleConfig, selection: PlatformAppSelection) throws
  func liftShield(reason: String) throws
  func startSession(durationSeconds: Int64, scope: PlatformShieldScope, strict: Bool) throws
  func endSession(overrideReason: String?) throws
  func setThresholds(thresholds: PlatformThresholds) throws
  /// Reads the last [days] days. Shaped to the iOS floor on both platforms.
  func readUsage(days: Int64) async throws -> PlatformUsage
  func trackingHealth() throws -> [PlatformTrackingCheck]
  /// Deletes everything the module holds on this device.
  ///
  /// Called by the retention sweep (§3.2) and by account deletion.
  func purgeLocalData(olderThanDays: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class UnplugHostApiSetup {
  static var codec: FlutterStandardMessageCodec { UnplugApiPigeonCodec.shared }
  /// Sets up an instance of `UnplugHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: UnplugHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// False on web, desktop, and any build without the screen-time layer. Dart
    /// falls back to its own simulation when this is false.
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.breathefree_patient.UnplugHostApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    let requestAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.breathefree_patient.UnplugHostApi.requestAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestAuthorizationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let modeArg = args[0] as! PlatformAuthorizationMode
        Task { @MainActor in
          do {
            let result = try await api.requestAuthorization(mode: modeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestAuthorizationChannel.setMessageHandler(nil)
    }
    let authorizationStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.breathefree_patient.UnplugHostApi.authorizationStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authorizationStatusChannel.setMessageHandler { _, reply in
        do {
          let result = try api.authorizationStatus()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      authorizationStatusChannel.setMessageHandler(nil)
    }
    /// Presents the system app picker. Returns the number of apps chosen.
    ///
    /// The picker is a system component on both platforms and cannot be drawn by
    /// Flutter, which is why this returns a count and not a list.
    let presentAppPickerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.breathefree_patient.UnplugHostApi.presentAppPicker\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      presentAppPickerChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.presentAppPicker()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      presentAppPickerChannel.setMessageHandler(nil)
    }
    let applyShieldChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.breathefree_patient.UnplugHostApi.applyShield\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      applyShieldChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! PlatformModuleConfig
        let selectionArg = args[1] as! PlatformAppSelection
        do {
          try api.applyShield(config: configArg, selection: selectionArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      applyShieldChannel.setMessageHandler(nil)
    }
    let liftShieldChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.breathefree_patient.UnplugHostApi.liftShield\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      liftShieldChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reasonArg = args[0] as! String
        do {
          try api.liftShield(reason: reasonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      liftShieldChannel.setMessageHandler(nil)
    }
    let startSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.breathefree_patient.UnplugHostApi.startSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let durationSecondsArg = args[0] as! Int64
        let scopeArg = args[1] as! PlatformShieldScope
        let strictArg = args[2] as! Bool
        do {
          try api.startSession(durationSeconds: durationSecondsArg, scope: scopeArg, strict: strictArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startSessionChannel.setMessageHandler(nil)
    }
    let endSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.breathefree_patient.UnplugHostApi.endSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let overrideReasonArg: String? = nilOrValue(args[0])
        do {
          try api.endSession(overrideReason: overrideReasonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      endSessionChannel.setMessageHandler(nil)
    }
    let setThresholdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.breathefree_patient.UnplugHostApi.setThresholds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setThresholdsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let thresholdsArg = args[0] as! PlatformThresholds
        do {
          try api.setThresholds(thresholds: thresholdsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setThresholdsChannel.setMessageHandler(nil)
    }
    /// Reads the last [days] days. Shaped to the iOS floor on both platforms.
    let readUsageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.breathefree_patient.UnplugHostApi.readUsage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readUsageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let daysArg = args[0] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.readUsage(days: daysArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      readUsageChannel.setMessageHandler(nil)
    }
    let trackingHealthChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.breathefree_patient.UnplugHostApi.trackingHealth\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackingHealthChannel.setMessageHandler { _, reply in
        do {
          let result = try api.trackingHealth()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      trackingHealthChannel.setMessageHandler(nil)
    }
    /// Deletes everything the module holds on this device.
    ///
    /// Called by the retention sweep (§3.2) and by account deletion.
    let purgeLocalDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.breathefree_patient.UnplugHostApi.purgeLocalData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      purgeLocalDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let olderThanDaysArg = args[0] as! Int64
        do {
          try api.purgeLocalData(olderThanDays: olderThanDaysArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      purgeLocalDataChannel.setMessageHandler(nil)
    }
  }
}

/// Callbacks the platform makes into Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol UnplugFlutterApiProtocol {
  func onThresholdCrossed(minutesUsed minutesUsedArg: Int64, opens opensArg: Int64) async throws
  func onShieldShown(groupLabel groupLabelArg: String) async throws
  func onShieldDismissed(groupLabel groupLabelArg: String) async throws
  func onOverrideUsed(groupLabel groupLabelArg: String, overridesRemaining overridesRemainingArg: Int64) async throws
  /// Fired when a health check starts failing, so the person is told rather
  /// than left believing the module is still running (§2.2).
  func onTrackingStopped(checkName checkNameArg: String, detail detailArg: String) async throws
}
class UnplugFlutterApi: UnplugFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: UnplugApiPigeonCodec {
    return UnplugApiPigeonCodec.shared
  }
  func onThresholdCrossed(minutesUsed minutesUsedArg: Int64, opens opensArg: Int64) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.breathefree_patient.UnplugFlutterApi.onThresholdCrossed\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([minutesUsedArg, opensArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onShieldShown(groupLabel groupLabelArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.breathefree_patient.UnplugFlutterApi.onShieldShown\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([groupLabelArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onShieldDismissed(groupLabel groupLabelArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.breathefree_patient.UnplugFlutterApi.onShieldDismissed\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([groupLabelArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  func onOverrideUsed(groupLabel groupLabelArg: String, overridesRemaining overridesRemainingArg: Int64) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.breathefree_patient.UnplugFlutterApi.onOverrideUsed\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([groupLabelArg, overridesRemainingArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  /// Fired when a health check starts failing, so the person is told rather
  /// than left believing the module is still running (§2.2).
  func onTrackingStopped(checkName checkNameArg: String, detail detailArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.breathefree_patient.UnplugFlutterApi.onTrackingStopped\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([checkNameArg, detailArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
